---
abstract: 'Pluggable IRC darkbot-alike'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Data::Dumper: 0
  Fcntl: 0
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  Test::Cmd: 0
  Test::Exception: 0
  Test::More: 0
  Try::Tiny: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-Cobalt
provides:
  Bot::Cobalt:
    file: lib/Bot/Cobalt.pm
    version: 0.015
  Bot::Cobalt::Common:
    file: lib/Bot/Cobalt/Common.pm
    version: 0.015
  Bot::Cobalt::Conf:
    file: lib/Bot/Cobalt/Conf.pm
    version: 0.015
  Bot::Cobalt::Conf::File:
    file: lib/Bot/Cobalt/Conf/File.pm
    version: 0.015
  Bot::Cobalt::Conf::File::Channels:
    file: lib/Bot/Cobalt/Conf/File/Channels.pm
    version: 0.015
  Bot::Cobalt::Conf::File::Core:
    file: lib/Bot/Cobalt/Conf/File/Core.pm
    version: 0.015
  Bot::Cobalt::Conf::File::PerPlugin:
    file: lib/Bot/Cobalt/Conf/File/PerPlugin.pm
    version: 0.015
  Bot::Cobalt::Conf::File::Plugins:
    file: lib/Bot/Cobalt/Conf/File/Plugins.pm
    version: 0.015
  Bot::Cobalt::Conf::Role::Reader:
    file: lib/Bot/Cobalt/Conf/Role/Reader.pm
    version: 0.015
  Bot::Cobalt::Core:
    file: lib/Bot/Cobalt/Core.pm
    version: 0.015
  Bot::Cobalt::Core::ContextMeta:
    file: lib/Bot/Cobalt/Core/ContextMeta.pm
    version: 0.015
  Bot::Cobalt::Core::ContextMeta::Auth:
    file: lib/Bot/Cobalt/Core/ContextMeta/Auth.pm
    version: 0.015
  Bot::Cobalt::Core::ContextMeta::Ignore:
    file: lib/Bot/Cobalt/Core/ContextMeta/Ignore.pm
    version: 0.015
  Bot::Cobalt::Core::Loader:
    file: lib/Bot/Cobalt/Core/Loader.pm
    version: 0.015
  Bot::Cobalt::Core::Role::EasyAccessors:
    file: lib/Bot/Cobalt/Core/Role/EasyAccessors.pm
    version: 0.015
  Bot::Cobalt::Core::Role::IRC:
    file: lib/Bot/Cobalt/Core/Role/IRC.pm
    version: 0.015
  Bot::Cobalt::Core::Role::Singleton:
    file: lib/Bot/Cobalt/Core/Role/Singleton.pm
    version: 0.015
  Bot::Cobalt::Core::Role::Timers:
    file: lib/Bot/Cobalt/Core/Role/Timers.pm
    version: 0.015
  Bot::Cobalt::Core::Sugar:
    file: lib/Bot/Cobalt/Core/Sugar.pm
    version: 0.015
  Bot::Cobalt::DB:
    file: lib/Bot/Cobalt/DB.pm
    version: 0.015
  Bot::Cobalt::Error:
    file: lib/Bot/Cobalt/Error.pm
    version: 0.015
  Bot::Cobalt::Frontend::RC:
    file: lib/Bot/Cobalt/Frontend/RC.pm
    version: 0.015
  Bot::Cobalt::Frontend::Utils:
    file: lib/Bot/Cobalt/Frontend/Utils.pm
    version: 0.015
  Bot::Cobalt::IRC:
    file: lib/Bot/Cobalt/IRC.pm
    version: 0.015
  Bot::Cobalt::IRC::Event:
    file: lib/Bot/Cobalt/IRC/Event.pm
    version: 0.015
  Bot::Cobalt::IRC::Event::Channel:
    file: lib/Bot/Cobalt/IRC/Event/Channel.pm
    version: 0.015
  Bot::Cobalt::IRC::Event::Kick:
    file: lib/Bot/Cobalt/IRC/Event/Kick.pm
    version: 0.015
  Bot::Cobalt::IRC::Event::Mode:
    file: lib/Bot/Cobalt/IRC/Event/Mode.pm
    version: 0.015
  Bot::Cobalt::IRC::Event::Nick:
    file: lib/Bot/Cobalt/IRC/Event/Nick.pm
    version: 0.015
  Bot::Cobalt::IRC::Event::Quit:
    file: lib/Bot/Cobalt/IRC/Event/Quit.pm
    version: 0.015
  Bot::Cobalt::IRC::Event::Topic:
    file: lib/Bot/Cobalt/IRC/Event/Topic.pm
    version: 0.015
  Bot::Cobalt::IRC::FloodChk:
    file: lib/Bot/Cobalt/IRC/FloodChk.pm
    version: 0.015
  Bot::Cobalt::IRC::Message:
    file: lib/Bot/Cobalt/IRC/Message.pm
    version: 0.015
  Bot::Cobalt::IRC::Message::Public:
    file: lib/Bot/Cobalt/IRC/Message/Public.pm
    version: 0.015
  Bot::Cobalt::IRC::Role::AdminCmds:
    file: lib/Bot/Cobalt/IRC/Role/AdminCmds.pm
    version: 0.015
  Bot::Cobalt::IRC::Role::UserEvents:
    file: lib/Bot/Cobalt/IRC/Role/UserEvents.pm
    version: 0.015
  Bot::Cobalt::IRC::Server:
    file: lib/Bot/Cobalt/IRC/Server.pm
    version: 0.015
  Bot::Cobalt::Logger:
    file: lib/Bot/Cobalt/Logger.pm
    version: 0.015
  Bot::Cobalt::Logger::Output:
    file: lib/Bot/Cobalt/Logger/Output.pm
    version: 0.015
  Bot::Cobalt::Logger::Output::File:
    file: lib/Bot/Cobalt/Logger/Output/File.pm
    version: 0.015
  Bot::Cobalt::Logger::Output::Term:
    file: lib/Bot/Cobalt/Logger/Output/Term.pm
    version: 0.015
  Bot::Cobalt::Plugin::Alarmclock:
    file: lib/Bot/Cobalt/Plugin/Alarmclock.pm
    version: 0.015
  Bot::Cobalt::Plugin::Auth:
    file: lib/Bot/Cobalt/Plugin/Auth.pm
    version: 0.015
  Bot::Cobalt::Plugin::Extras::CPAN:
    file: lib/Bot/Cobalt/Plugin/Extras/CPAN.pm
    version: 0.015
  Bot::Cobalt::Plugin::Extras::DNS:
    file: lib/Bot/Cobalt/Plugin/Extras/DNS.pm
    version: 0.015
  Bot::Cobalt::Plugin::Extras::Debug:
    file: lib/Bot/Cobalt/Plugin/Extras/Debug.pm
    version: 0.015
  Bot::Cobalt::Plugin::Extras::Karma:
    file: lib/Bot/Cobalt/Plugin/Extras/Karma.pm
    version: 0.015
  Bot::Cobalt::Plugin::Extras::Money:
    file: lib/Bot/Cobalt/Plugin/Extras/Money.pm
    version: 0.015
  Bot::Cobalt::Plugin::Extras::Relay:
    file: lib/Bot/Cobalt/Plugin/Extras/Relay.pm
    version: 0.015
  Bot::Cobalt::Plugin::Extras::Shorten:
    file: lib/Bot/Cobalt/Plugin/Extras/Shorten.pm
    version: 0.015
  Bot::Cobalt::Plugin::Extras::TempConv:
    file: lib/Bot/Cobalt/Plugin/Extras/TempConv.pm
    version: 0.015
  Bot::Cobalt::Plugin::Games:
    file: lib/Bot/Cobalt/Plugin/Games.pm
    version: 0.015
  Bot::Cobalt::Plugin::Games::Dice:
    file: lib/Bot/Cobalt/Plugin/Games/Dice.pm
    version: 0.015
  Bot::Cobalt::Plugin::Games::Magic8:
    file: lib/Bot/Cobalt/Plugin/Games/Magic8.pm
    version: 0.015
  Bot::Cobalt::Plugin::Games::RockPaperScissors:
    file: lib/Bot/Cobalt/Plugin/Games/RockPaperScissors.pm
    version: 0.015
  Bot::Cobalt::Plugin::Games::Roulette:
    file: lib/Bot/Cobalt/Plugin/Games/Roulette.pm
    version: 0.015
  Bot::Cobalt::Plugin::Info3:
    file: lib/Bot/Cobalt/Plugin/Info3.pm
    version: 0.015
  Bot::Cobalt::Plugin::Master:
    file: lib/Bot/Cobalt/Plugin/Master.pm
    version: 0.015
  Bot::Cobalt::Plugin::OutputFilters::StripColor:
    file: lib/Bot/Cobalt/Plugin/OutputFilters/StripColor.pm
    version: 0.015
  Bot::Cobalt::Plugin::OutputFilters::StripFormat:
    file: lib/Bot/Cobalt/Plugin/OutputFilters/StripFormat.pm
    version: 0.015
  Bot::Cobalt::Plugin::PluginMgr:
    file: lib/Bot/Cobalt/Plugin/PluginMgr.pm
    version: 0.015
  Bot::Cobalt::Plugin::RDB:
    file: lib/Bot/Cobalt/Plugin/RDB.pm
    version: 0.015
  Bot::Cobalt::Plugin::RDB::AsyncSearch:
    file: lib/Bot/Cobalt/Plugin/RDB/AsyncSearch.pm
    version: 0.015
  Bot::Cobalt::Plugin::RDB::AsyncSearch::Worker:
    file: lib/Bot/Cobalt/Plugin/RDB/AsyncSearch/Worker.pm
    version: 0.015
  Bot::Cobalt::Plugin::RDB::Database:
    file: lib/Bot/Cobalt/Plugin/RDB/Database.pm
    version: 0.015
  Bot::Cobalt::Plugin::RDB::SearchCache:
    file: lib/Bot/Cobalt/Plugin/RDB/SearchCache.pm
    version: 0.015
  Bot::Cobalt::Plugin::Rehash:
    file: lib/Bot/Cobalt/Plugin/Rehash.pm
    version: 0.015
  Bot::Cobalt::Plugin::Seen:
    file: lib/Bot/Cobalt/Plugin/Seen.pm
    version: 0.015
  Bot::Cobalt::Plugin::Version:
    file: lib/Bot/Cobalt/Plugin/Version.pm
    version: 0.015
  Bot::Cobalt::Plugin::WWW:
    file: lib/Bot/Cobalt/Plugin/WWW.pm
    version: 0.015
  Bot::Cobalt::Serializer:
    file: lib/Bot/Cobalt/Serializer.pm
    version: 0.015
  Bot::Cobalt::Timer:
    file: lib/Bot/Cobalt/Timer.pm
    version: 0.015
  Bot::Cobalt::Utils:
    file: lib/Bot/Cobalt/Utils.pm
    version: 0.015
recommends:
  POE::Component::SSLify: 1.006
requires:
  App::bmkpasswd: 1.06
  Carp: 0
  Cwd: 0
  DB_File: 0
  Data::Dumper: 0
  Devel::StackTrace: 1.27
  Exporter: 0
  Fcntl: 0
  File::Find: 0
  File::Path: 2.00
  File::Spec: 0
  Getopt::Long: 0
  HTTP::Request: 0
  HTTP::Response: 0
  IO::File: 0
  IRC::Utils: 0.12
  JSON::XS: 2.00
  List::Util: 0
  Module::CoreList: 0
  Moo: 0.091009
  MooX::Types::MooseLike: 0.08
  Net::IP::Minimal: 0.04
  Object::Pluggable: 1.27
  POE: 1.311
  POE::Component::Client::DNS: 0
  POE::Component::Client::HTTP: 0.947
  POE::Component::Client::Keepalive: 0
  POE::Component::IRC::State: 6.78
  POE::Component::Resolver: 0.920
  POE::Component::Syndicator: 0.06
  POSIX: 0
  Proc::PID::File: 1.26
  Scalar::Util: 0
  Storable: 0
  Term::ReadKey: 0
  Time::HiRes: 0
  Try::Tiny: 0
  URI::Escape: 0
  YAML::XS: 0.34
  namespace::clean: 0
  overload: 0
  perl: v5.12.1
  strictures: 1
resources:
  license: http://dev.perl.org/licenses/
version: 0.015
